#!/bin/sh /etc/rc.common

APP=/usr/sbin/mqtt_sub
USE_PROCD=1
START=99
STOP=99

setup_config() {
	config_load mqtt_sub
	config_get enabled "mqtt_sub" enabled "0"
}

start_service() {
	setup_config
	if [ "$enabled" == "1" ]; then
		procd_open_instance
		procd_set_param command /usr/sbin/mqtt_sub
		procd_set_param respawn ${respawn_threshold:-0} ${respawn_timeout:-60} ${respawn_retry:-0}
		procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "mqtt_sub"
}
